//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public string Id { get; set; }
        public string UserCode { get; set; }
        public string ProfileImagePath { get; set; }
        public string ThumbnailPath { get; set; }
        public int UserStatusID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public int UserSequence { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public int CountryID { get; set; }
        public string PIN { get; set; }
        public bool IsPinVerified { get; set; }
        public bool IsIDVerified { get; set; }
        public string IDCardNumber { get; set; }
        public string Comments { get; set; }
        public System.DateTime PinVerifiedDate { get; set; }
        public Nullable<System.DateTime> EmailVerifiedDate { get; set; }
        public Nullable<System.DateTime> PhoneVerifiedDate { get; set; }
        public System.DateTime IDExpiredDate { get; set; }
        public Nullable<System.DateTime> IDVerifiedDate { get; set; }
        public string BuildingNo { get; set; }
        public string StreetNo { get; set; }
        public string Zone { get; set; }
        public string StreetName { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserType { get; set; }
        public string DigitalSignature { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PlaceOfBirth { get; set; }
        public string HomeNumber { get; set; }
        public Nullable<System.DateTime> QIDExpiry { get; set; }
        public string QIDFrontImagePath { get; set; }
        public string QIDBackImagePath { get; set; }
        public string PassportImageFront { get; set; }
        public Nullable<System.DateTime> QPANExpiry { get; set; }
        public int AccountLevelID { get; set; }
        public Nullable<bool> PassportVerified { get; set; }
        public Nullable<System.DateTime> PassportVerifiedDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public Nullable<int> PassportExpiryReminderType { get; set; }
        public Nullable<int> QIDExpiryReminderType { get; set; }
    }
}
