//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public string CountryName { get; set; }
        public string CountryNameArabic { get; set; }
        public string Alpha_2 { get; set; }
        public string Alpha_3_Code { get; set; }
        public string UN_Code { get; set; }
    }
}
