//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QatarPayEntities : DbContext
    {
        public QatarPayEntities()
            : base("name=QatarPayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountLevel> AccountLevels { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BankDetail> BankDetails { get; set; }
        public virtual DbSet<BankList> BankLists { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Country1> Countries1 { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyRate> CurrencyRates { get; set; }
        public virtual DbSet<DeviceToken> DeviceTokens { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DtOneTransactionResponse> DtOneTransactionResponses { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceBillingRequest> InvoiceBillingRequests { get; set; }
        public virtual DbSet<InvoiceBillingResponse> InvoiceBillingResponses { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<InvoicePaymentRequest> InvoicePaymentRequests { get; set; }
        public virtual DbSet<InvoicePaymentStatu> InvoicePaymentStatus { get; set; }
        public virtual DbSet<IplayinTransaction> IplayinTransactions { get; set; }
        public virtual DbSet<KaharmaNumbersInGroup> KaharmaNumbersInGroups { get; set; }
        public virtual DbSet<KarwaBusPayment> KarwaBusPayments { get; set; }
        public virtual DbSet<KarwaBusRequest> KarwaBusRequests { get; set; }
        public virtual DbSet<KarwaUserBusCard> KarwaUserBusCards { get; set; }
        public virtual DbSet<LogType> LogTypes { get; set; }
        public virtual DbSet<LoyaltyBrand> LoyaltyBrands { get; set; }
        public virtual DbSet<MerchantPaymentItemDetail> MerchantPaymentItemDetails { get; set; }
        public virtual DbSet<MerchantPaymentRequest> MerchantPaymentRequests { get; set; }
        public virtual DbSet<MerchantPaymentResponse> MerchantPaymentResponses { get; set; }
        public virtual DbSet<MerchantProfile> MerchantProfiles { get; set; }
        public virtual DbSet<MerchantRefund> MerchantRefunds { get; set; }
        public virtual DbSet<NoqsQRTransferRequest> NoqsQRTransferRequests { get; set; }
        public virtual DbSet<NoqsTopupRequest> NoqsTopupRequests { get; set; }
        public virtual DbSet<NoqsTransferRequestLog> NoqsTransferRequestLogs { get; set; }
        public virtual DbSet<NoticeBoard> NoticeBoards { get; set; }
        public virtual DbSet<NotificationsType> NotificationsTypes { get; set; }
        public virtual DbSet<ParkingRequestLog> ParkingRequestLogs { get; set; }
        public virtual DbSet<PaymentCard> PaymentCards { get; set; }
        public virtual DbSet<PaymentCardType> PaymentCardTypes { get; set; }
        public virtual DbSet<PaymentRequest> PaymentRequests { get; set; }
        public virtual DbSet<PaymentResponse> PaymentResponses { get; set; }
        public virtual DbSet<PhoneNumbersInGroup> PhoneNumbersInGroups { get; set; }
        public virtual DbSet<QatarCoolNumbersInGroup> QatarCoolNumbersInGroups { get; set; }
        public virtual DbSet<QatarMetroUserCard> QatarMetroUserCards { get; set; }
        public virtual DbSet<QParkingTransaction> QParkingTransactions { get; set; }
        public virtual DbSet<ResetPasswordRequest> ResetPasswordRequests { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceCategory> ServiceCategories { get; set; }
        public virtual DbSet<ServiceCharge> ServiceCharges { get; set; }
        public virtual DbSet<ServiceMerchantAccount> ServiceMerchantAccounts { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShopOrder> ShopOrders { get; set; }
        public virtual DbSet<ShopOrderDetail> ShopOrderDetails { get; set; }
        public virtual DbSet<ShopOrderPayment> ShopOrderPayments { get; set; }
        public virtual DbSet<ShopProduct> ShopProducts { get; set; }
        public virtual DbSet<SmsLog> SmsLogs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<SystemRequest> SystemRequests { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<SystemUsersLog> SystemUsersLogs { get; set; }
        public virtual DbSet<TemporaryImageLocation> TemporaryImageLocations { get; set; }
        public virtual DbSet<TopupPaymentSetting> TopupPaymentSettings { get; set; }
        public virtual DbSet<TopUpRequest> TopUpRequests { get; set; }
        public virtual DbSet<TopUpSetting> TopUpSettings { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionsDesc> TransactionsDescs { get; set; }
        public virtual DbSet<TransactionsLedger> TransactionsLedgers { get; set; }
        public virtual DbSet<TransactionStatu> TransactionStatus { get; set; }
        public virtual DbSet<TransactionsType> TransactionsTypes { get; set; }
        public virtual DbSet<UserDocument> UserDocuments { get; set; }
        public virtual DbSet<UserDrivingLicense> UserDrivingLicenses { get; set; }
        public virtual DbSet<UserIDCard> UserIDCards { get; set; }
        public virtual DbSet<UserInvoice> UserInvoices { get; set; }
        public virtual DbSet<UserKaharmaGroup> UserKaharmaGroups { get; set; }
        public virtual DbSet<UserLocation> UserLocations { get; set; }
        public virtual DbSet<UserLoyaltyCard> UserLoyaltyCards { get; set; }
        public virtual DbSet<UserPassport> UserPassports { get; set; }
        public virtual DbSet<UserPhoneGroup> UserPhoneGroups { get; set; }
        public virtual DbSet<UserQatarCoolGroup> UserQatarCoolGroups { get; set; }
        public virtual DbSet<UserShop> UserShops { get; set; }
        public virtual DbSet<UserShopProduct> UserShopProducts { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<WoqoodyConfirmOrderRequest> WoqoodyConfirmOrderRequests { get; set; }
        public virtual DbSet<WoqoodyLogin> WoqoodyLogins { get; set; }
        public virtual DbSet<WoqoodyRequestOrder> WoqoodyRequestOrders { get; set; }
        public virtual DbSet<AppBanner> AppBanners { get; set; }
    }
}
