//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceBillingRequest
    {
        public int ID { get; set; }
        public int InvoiceRequestID { get; set; }
        public int ReferenceID { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int UserID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public bool IsConsumed { get; set; }
        public string URL { get; set; }
        public string TransactionReferenceNo { get; set; }
    }
}
