//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceBillingResponse
    {
        public int ID { get; set; }
        public string InvoiceNumber { get; set; }
        public int InvoiceBillingRequestID { get; set; }
        public string Status { get; set; }
        public string OperatorResponse { get; set; }
        public string OperatorReference { get; set; }
        public bool TransactionStatus { get; set; }
        public decimal TransasctionAmount { get; set; }
        public string TransasctionCode { get; set; }
        public string TransactionMessage { get; set; }
        public string TransactionService { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionDescription { get; set; }
        public string TransactionInvoice { get; set; }
        public string InvoiceDescription { get; set; }
        public decimal InvoiceAmount { get; set; }
        public System.DateTime EntryTime { get; set; }
        public string IPAddress { get; set; }
        public string ResponseFrom { get; set; }
        public int UserID { get; set; }
    }
}
