//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePaymentRequest
    {
        public int ID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestSource { get; set; }
        public int InvoiceID { get; set; }
        public int UserID { get; set; }
        public string ReferenceNo { get; set; }
        public decimal Amount { get; set; }
        public int Counter { get; set; }
        public System.DateTime EntryTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public string Description { get; set; }
        public bool IsConsumed { get; set; }
        public System.DateTime CompletedDate { get; set; }
    }
}
