//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime InvoiceDueDate { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceDescription { get; set; }
        public decimal InvoiceTotal { get; set; }
        public int UserID { get; set; }
        public int InvoiceStatus { get; set; }
        public decimal Discount { get; set; }
        public decimal InvoiceAmount { get; set; }
        public string InvoiceNote { get; set; }
        public int AddressID { get; set; }
        public string RecipitantName { get; set; }
        public string RecipitantCompany { get; set; }
        public string RecipitantAddress { get; set; }
        public string RecipitantEmail { get; set; }
        public string RecipitantMobile { get; set; }
        public bool IsEmailSend { get; set; }
        public bool IsSmsSend { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int ModifiedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    }
}
