//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class KaharmaNumbersInGroup
    {
        public int ID { get; set; }
        public int GroupID { get; set; }
        public int UserID { get; set; }
        public string QID { get; set; }
        public string SubscriberName { get; set; }
        public string SubscriberNameArabic { get; set; }
        public string KaharmaNumber { get; set; }
        public int OperatorID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public decimal BillingAmount { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
    }
}
