//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantProfile
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string Fax { get; set; }
        public string Telephone { get; set; }
        public string BankAccount { get; set; }
        public string BankName { get; set; }
        public string OtherInfo { get; set; }
        public int CountryID { get; set; }
    }
}
