//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantPaymentResponse
    {
        public int ID { get; set; }
        public int MerchantPaymentRequestID { get; set; }
        public string TransactionDescription { get; set; }
        public string MerchantReference { get; set; }
        public string TransactionNumber { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyID { get; set; }
        public string PlatForm { get; set; }
        public System.DateTime TransactionCompletedDate { get; set; }
        public string MerchantDefinedData { get; set; }
        public int PaidUserID { get; set; }
        public string TransactionHash { get; set; }
        public string RedirectURL { get; set; }
        public bool TransactionStatus { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionResponseMessage { get; set; }
        public string TransactionQRCode { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int UserID { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    }
}
