//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantPaymentRequest
    {
        public int ID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int UserID { get; set; }
        public string MerchantReference { get; set; }
        public string MerchantDefinedData { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyID { get; set; }
        public string SessionID { get; set; }
        public string UUID { get; set; }
        public string SecureHash { get; set; }
        public string TransactionDescription { get; set; }
        public string QRCodeData { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int ModifedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsCompleted { get; set; }
        public int RequestStatusID { get; set; }
    }
}
