//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantRefund
    {
        public int ID { get; set; }
        public int MerchantTransactionID { get; set; }
        public int RefundTransactionID { get; set; }
        public string RefundNumber { get; set; }
        public System.DateTime RefundDate { get; set; }
        public string Description { get; set; }
        public decimal ActualAmout { get; set; }
        public decimal RefundedAmount { get; set; }
        public int UserID { get; set; }
        public int RefundToUserID { get; set; }
        public string RefundReason { get; set; }
        public System.DateTime EntryTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public int ModifiedBy { get; set; }
    }
}
