//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeBoard
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Notice { get; set; }
        public string Title { get; set; }
        public int StatusID { get; set; }
        public bool IsReadByUser { get; set; }
        public int NotificationType { get; set; }
        public System.DateTime EntryTime { get; set; }
        public System.DateTime SchduledTime { get; set; }
        public int SentByUserID { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public int ReferenceID { get; set; }
        public int ReferenceStatusID { get; set; }
    }
}
