//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        public int ID { get; set; }
        public string CardName { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int ModifiedBy { get; set; }
        public int UserID { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public string OwnerName { get; set; }
        public string ExpiryDate { get; set; }
        public string CVV { get; set; }
        public Nullable<int> PaymentCardType { get; set; }
        public string ReminderType { get; set; }
    }
}
