//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class QParkingTransaction
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string ReferenceNumber { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string IPAddress { get; set; }
        public bool IsConsumed { get; set; }
        public string MerchantReference { get; set; }
        public string RawResponse { get; set; }
        public int TransactionID { get; set; }
        public int LedgerID { get; set; }
        public int SellerTransactionID { get; set; }
        public int SellerLedgerID { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal Discount { get; set; }
        public int MerchantID { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public System.DateTime EntryTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public int ModifiedBy { get; set; }
        public string TicketNumber { get; set; }
        public string ClientReference { get; set; }
        public string TransactionReference { get; set; }
        public decimal AmountPaid { get; set; }
    }
}
