//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPasswordRequest
    {
        public int ID { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public string UserCode { get; set; }
        public System.DateTime RequestValidity { get; set; }
        public bool IsConsumed { get; set; }
        public System.DateTime EntryTime { get; set; }
        public string Description { get; set; }
    }
}
