//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategory
    {
        public int ID { get; set; }
        public string ServiceCategoryName { get; set; }
        public string ServiceCategoryNameArabic { get; set; }
        public string Description { get; set; }
        public string DescriptionArabic { get; set; }
        public string ThumbnailLocation { get; set; }
        public string ImageLocation { get; set; }
        public bool IsActive { get; set; }
        public bool ShowInApp { get; set; }
        public int UserID { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    }
}
