//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCharge
    {
        public int ID { get; set; }
        public int TransactionTypeID { get; set; }
        public decimal ServiceCharges { get; set; }
        public bool ChrageByPercentage { get; set; }
    }
}
