//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopOrderPayment
    {
        public int ID { get; set; }
        public System.DateTime PaymentRequestDate { get; set; }
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public decimal Amount { get; set; }
        public bool TransactionStatus { get; set; }
        public string PaymentDescription { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerMobilePhone { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime PaymentCompletedDate { get; set; }
        public string SessionID { get; set; }
        public string UUID { get; set; }
        public string IPAddress { get; set; }
        public string RawResponse { get; set; }
        public string PlatForm { get; set; }
        public string TransactionMessage { get; set; }
        public decimal TransactionFee { get; set; }
        public decimal ServiceCharge { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    }
}
