//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsLog
    {
        public int ID { get; set; }
        public string MsgText { get; set; }
        public string Destination { get; set; }
        public string ResponseStatus { get; set; }
        public string MessageType { get; set; }
        public System.DateTime Entrytime { get; set; }
        public int UserID { get; set; }
    }
}
