//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUsersLog
    {
        public int ID { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public int UserID { get; set; }
        public string PageVisited { get; set; }
        public string Description { get; set; }
    }
}
