//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRequest
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string RequestCode { get; set; }
        public string RequestType { get; set; }
        public string AccessToken { get; set; }
        public string ClientReferenceID { get; set; }
        public bool IsConsumed { get; set; }
        public System.DateTime EntryTime { get; set; }
    }
}
