//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemporaryImageLocation
    {
        public int ID { get; set; }
        public string OrignalFileLocation { get; set; }
        public string ThumbnailLocation { get; set; }
        public string MediamFileLocation { get; set; }
        public System.DateTime EntryTime { get; set; }
    }
}
