//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInvoice
    {
        public int ID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string MobileNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNameArabic { get; set; }
        public string Company { get; set; }
        public string CustomerEmail { get; set; }
        public string InvoiceDescription { get; set; }
        public string InvoiceDescriptionArabic { get; set; }
        public decimal OtherCharges { get; set; }
        public string OtherChangesDescription { get; set; }
        public string OtherChangesDescriptionArabic { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal DiscountedAmount { get; set; }
        public decimal Amount { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalAmount { get; set; }
        public int UserID { get; set; }
        public int PaidStatus { get; set; }
        public int PaidTransactionID { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime EntryTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public bool IsEmailSend { get; set; }
        public bool IsSmsSend { get; set; }
        public string InvoiceReference { get; set; }
        public bool IsCunsumed { get; set; }
        public decimal ServiceCharges { get; set; }
        public int PaymentMethodID { get; set; }
    }
}
