//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QatarPayAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WoqoodyRequestOrder
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> WoqoodyAddressID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> CylinderSizeID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> LaunguageID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> RequestID { get; set; }
    }
}
